
export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const POST_PRODUCT_SUCRSS = "POST_PRODUCT_SUCRSS";
export const PRODUCT_ERROR = "PRODUCT_ERROR";

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST"

export const DELETE_PRODUCTS_REQUEST = "DELETE_PRODUCTS_REQUEST"

export const PATCH_PRODUCTS_REQUEST = "PATCH_PRODUCTS_REQUEST"